### ISSUE TITLE
About the search results

### ISSUE THREAD

**Issue by YiningWang2** [stivalaa/cuda_satabsearch#2]
Hello, i have another problem. Can i get the sub protein pdb structure from this tool. Thanks so much.

**Comment by stivalaa** [comment]
Yes, you need to change one of the logical (Boolean) options in the query. As described in the README.md file:

Both the name of the database file to read, and the actual query tableau are read from stdin. The first line is the name of the database file. The second line is for options. There are currently 3 logical options, for SSE type constraint (only allow SSEs of same type to match) and ordering constraint (disallow out of sequence order matches). The third is to output not just the scores but also solution vector values. They are single character logical values (T or F). First is type, second is order, third is solution output, separated by one space.

The examples usually have T T F meaning that (1) type constraint is enforced, (2) order constraint is enforced, but (3) solution is not output, only score. So all you have to do is change the third value from F to T instead to output the solution, i.e. T T T instead of T T F.

There is an example file d1ubia_.input that demonstrates this:

```
/home/stivala/tableauxdistmatrixdb-sel-gs-bib-95-1.75.sorted.ascii
T T T
D1UBIA_    8
e
OT e
LE RT xa
PD OS RD xg
RT LE RT LS e
LE RD LE LS OT e
RT LS LS RD PE OS xg
PE RT LE RD OT PE RT e
 0.000
 4.501  0.000
11.662 10.386  1.000
16.932 17.644  9.779  3.000
10.588 13.738 11.815 10.527  0.000
15.025 18.692 17.143 15.341  6.466  0.000
15.298 17.276 16.276 20.075 13.264 11.610  3.000
 7.549 11.072 12.248 12.446  4.583  9.903 15.689  0.000
```

The last T on the second line means the solution is shown (if it is F then it is not shown).

But note this only shows SSE matchings, i.e. the correspondences of the secondary structure elements, as that is the level that the algorithm operates on. Furthermore, it is just in the form of a binary vector showing whether or not each SSE in the database structure matches the query struct. The solnssemap.py script reads this output and converts it to a mapping between the SSEs in the two structurses. The output of this script can then be fed into another script such as ssemap2pml.py, which reads this and conerts it to a PyMOL script to visualize the mapping. 

The output of soln2ssemap.py can also be fed into the superimposessemap.py script to do a superimposition of the residues as a PDB file which can be used for visualization, and it also calculates the RMSD of the superimposition (alignment).

**Comment by stivalaa** [comment]
Actually the solnssemap.py script is not needed for cudaSaTabsearch, which outputs in the SSE alignment by sequential SSE numbers already (my original FORTRAN-77 code for QP tableau search output the binary vector format which this script needed to convert). 

```
[stivala@icslogin01 nvcc_src_current]$ ./cudaSaTabsearch  -c < d1ubia_.input
MAXDIM = 111 (edit in saparams.h and recompile to change)
Read 1 query structures
Loading database...
Loaded 1 db entries (0 order > 96) in 0.068000 ms
maxstart = 128
# cudaSaTabsearch LTYPE = T LORDER = T LSOLN = T
# QUERY ID = D1UBIA_
# DBFILE = tableauxdistmatrixdb.test.ascii                                      
Executing simulated annealing tableaux match kernel on host for query D1UBIA_...
running on host
host execution time 1.278000 ms
10.015649 million iterations/sec
d1ndda_  14 1.75 0.903563 0.161558
  6   2
  7   4
  8   5

```

which shows that SSE sequentially numbered 6 in the query (d1ubia_) matches number 2 in the database structure (d1ndda_), 7 matches 4, etc.

Then the other scripts process this to do superimpositions (alignments), calculate RMSD, etc. However these scripts use the Python Bio.PDB library to read SCOP and ASTRAL data, so these have to be installed on your system (and if not in default locations you need to edit scripts/pathdefs.py to say where they are). And of course these databases should be the same ones used for building the tableaux etc.

**Comment by stivalaa** [comment]
I would also recommend changing the number of restarts to a much higher value than the default (128). E.g. 1024 (see paper for details on tradeoff between speed and accuracy). If you do this you are likely to get a much better result, e.g.:


```
[stivala@icslogin01 nvcc_src_current]$ ./cudaSaTabsearch  -c -r 1024 < d1ubia_.input
MAXDIM = 111 (edit in saparams.h and recompile to change)
Read 1 query structures
Loading database...
Loaded 1 db entries (0 order > 96) in 0.065000 ms
maxstart = 1024
# cudaSaTabsearch LTYPE = T LORDER = T LSOLN = T
# QUERY ID = D1UBIA_
# DBFILE = tableauxdistmatrixdb.test.ascii                                      
Executing simulated annealing tableaux match kernel on host for query D1UBIA_...
running on host
host execution time 9.767000 ms
10.484284 million iterations/sec
d1ndda_  22 2.75 3.07991 0.0107511
  4   4
  5   5
  6   6
  7   7
  8   8

```
Note the score is higher and now the p-value is significant (p < 0.05) which it was not before. And we can see the SSE alignment is an identity for a subset of the SSEs, which is more what we would expect here as they are both ubiquitin structures.

**Comment by stivalaa** [comment]
I haven't looked at these scripts (which I wrote around 2008 during my PhD) for a long time (although they are still running on the Pro-origami server after all this time http://munk.cis.unimelb.edu.au/pro-origami/) for a long time, so it took me a bit of reading my own comments to remember how to use them.

There are a lot of options, and things are more complicated if you allow "out of order" SSE matchings or use query "motifs" (subsets of query structures, rather than the whole query structure). The qptabmatsructs.sh which runs cudaSaTabSearch (or QP tableau matching, the FORTRAN program TSRCHD) on two PDB structures and then processes the output with the appropriate scripts to generate visualizations of the matchings and protein alignments shows how it all fits together.

I did discover that not all the scripts had the required -5 option to handle the new 5-column (raw score, normalized score, z-score, p-value) rather than the original 2-column (name, rawscore) format though, so I updated the superimposessemap.py and sse2map2pml scripts in GitHub to have this option.

This means you can now use them like this:

```
[stivala@icslogin01 nvcc_src_current]$ ./cudaSaTabsearch -c -r 1024 < d1ubia_.in
put |  python2 ../scripts/superimposessemap.py -5  -u /scratch/stivala/d1ubia_.e
nt -b /scratch/stivala/d1ndda_.ent  -o /scratch/stivala                        
MAXDIM = 111 (edit in saparams.h and recompile to change)                      
Read 1 query structures
Loading database...
Loaded 1 db entries (0 order > 96) in 0.076000 ms                              
maxstart = 1024
Executing simulated annealing tableaux match kernel on host for query D1UBIA_...
running on host
host execution time 9.826000 ms
10.421331 million iterations/sec
 !!! Residue GLY   76 A has  1 instead of expected   0 sidechain atoms.        
     last sidechain atom name is  OXT
     calculated solvent accessibility includes extra atoms !!!                 

 !!! COMPOUND-card missing !!!
 !!! SOURCE-card missing !!!
 !!! AUTHOR-card missing !!!
 !!! COMPOUND-card missing !!!
 !!! SOURCE-card missing !!!
 !!! AUTHOR-card missing !!!
d1ndda_  22.0000    5    5   0.29
[stivala@icslogin01 nvcc_src_current]$ head -16 /scratch/stivala/d1ubia__d1ndda_.pdb
REMARK generated by superimposessemap.py                                       
REMARK on 23Sep2022 07:13:59
REMARK
REMARK d1ndda_ superimposed on d1ubia_
REMARK SCORE =  22.0000
REMARK NSSES =    5
REMARK NRES =    5
REMARK RMSD =   0.29
REMARK
REMARK from:
REMARK # cudaSaTabsearch LTYPE = T LORDER = T LSOLN = T                        
REMARK # QUERY ID = D1UBIA_
REMARK # DBFILE = tableauxdistmatrixdb.test.ascii                              
ATOM      1  N   MET A   1      27.892  24.292   2.821  1.00 28.20           N 
ATOM      2  CA  MET A   1      26.750  24.987   3.482  1.00 26.45           C 
ATOM      3  C   MET A   1      27.268  26.296   4.068  1.00 23.57           C 
[stivala@icslogin01 nvcc_src_current]$
```
This output shows that the RMSD is 0.29 Angstroms.

Note that the PDB file generated by superimposessemap.py only contains the database structure translated and rotated by orthogonal transformations (with SVD) minimize the RMSD between atoms in the matched SSEs of the query and database structure. It does not contain the query structure. So to visualize, you need to load the original query structure and also the superimposed database structure in the output PDB file. E.g. in PyMOL (having downloaded the query structure d1ubia_.ent and the superimposessmap.py output dubia__d1ndda_.pdb into /var/tmp on the laptop):

```
alex@alex-Inspiron-15-3567:~$ pymol /var/tmp/d1ubia_.ent  /var/tmp/d1ubia__d1ndda_.pdb 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
 PyMOL(TM) Molecular Graphics System, Version 2.5.0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Detected OpenGL version 4.6. Shaders available.
 Geometry shaders not available
 Detected GLSL version 4.60.
 OpenGL graphics engine:
  GL_VENDOR:   Intel
  GL_RENDERER: Mesa Intel(R) HD Graphics 620 (KBL GT2)
  GL_VERSION:  4.6 (Compatibility Profile) Mesa 22.0.5
 Detected 4 CPU cores.  Enabled multithreaded rendering.
 CmdLoad: "" loaded as "d1ubia_".
 CmdLoad: "" loaded as "d1ubia__d1ndda_".
```
![image](https://user-images.githubusercontent.com/1900580/191897472-6fe7f917-9e42-49f1-95af-91c1661ab288.png)

**Comment by stivalaa** [comment]
Also you should note that the RMSD reported by the superimposessemap.py is not the standard use of RMSD you get for an alignment quality (of all the C_alpha backbone atoms for example), but just the RMSD of the very small number of atoms representing the SSEs that the algorithm aligns (only 5 in this case) - this RMSD is not for reporting alignment quality it is just a diagnostic showing the value that was minimized.

For details see the original QP tableau search paper (the CUDA SA tableau search is a heuristic algorithm implemented on the GPU for approximating the solution of the same quadratic integer problem):


Stivala, A., Wirth, A. & Stuckey, P.J. Tableau-based protein substructure search using quadratic programming. BMC Bioinformatics 10, 153 (2009). https://doi.org/10.1186/1471-2105-10-153

**Comment by stivalaa** [comment]
closed?
